video: rockchip: rga3: Import namespace DMA_BUF
ERROR: modpost: module rga3 uses symbol dma_buf_vmap from namespace DMA_BUF, but does not import it.
ERROR: modpost: module rga3 uses symbol dma_buf_vunmap from namespace DMA_BUF, but does not import it.
ERROR: modpost: module rga3 uses symbol dma_buf_attach from namespace DMA_BUF, but does not import it.
ERROR: modpost: module rga3 uses symbol dma_buf_map_attachment from namespace DMA_BUF, but does not import it.
ERROR: modpost: module rga3 uses symbol dma_buf_detach from namespace DMA_BUF, but does not import it.
ERROR: modpost: module rga3 uses symbol dma_buf_put from namespace DMA_BUF, but does not import it.
ERROR: modpost: module rga3 uses symbol dma_buf_get from namespace DMA_BUF, but does not import it.
ERROR: modpost: module rga3 uses symbol dma_buf_unmap_attachment from namespace DMA_BUF, but does not import it.

Signed-off-by: Tao Huang <huangtao@rock-chips.com>
Change-Id: I3fbad697bb9419f91f82d1aa5af087132c07cca7
(cherry picked from commit 2ca6c6255ff9bc9fcf60327701483b845bf1158a)